name: flutter_sodium
description: Flutter bindings for libsodium, a modern, easy-to-use crypto library.
version: 0.0.8
author: First Floor Software <info@firstfloorsoftware.com>
homepage: https://github.com/firstfloorsoftware/flutter_sodium

environment:
  sdk: '>=2.0.0-dev <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.firstfloorsoftware.fluttersodium
    pluginClass: FlutterSodiumPlugin
